sudo: required
dist: trusty
addons:
  apt:
    update: true
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - stable
before_install:
  - npm i -g npm
  - npm i -g live-server@1
  - npm i -g node-gyp@3
install:
  - npm install
script:
  - npm run test
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
after_success:
  - npm run ghpages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $PUSH_TOKEN
  on:
    branch: master
